main: dtmproject.DTM
name: DTM
version: ${project.version}
author: Juubes
depends:
- Nexus
database: true
api-version: 1.12.2
commands:
   setmonument: {}
   DTM: {}
   top: {}
   createmap: {}
   shop:
      aliases:
      - s
   join:
      aliases:
      - liity
   spec:
      aliases:
      - spectate
      - leave
   pause: null
   getpos: null
   worlds: null
   world: null
   stats: null
   nextmap: null
   setlobby: null
   editmode: null
   savekit:
      aliases:
      - gameinventory
   addteam: null
   removeteam:
      aliases:
      - delteam
   setteamspawn:
      aliases:
      - setspawn
   start: null
   setprefix: null
   savemap: null
   playtime:
      aliases:
      - gametime