CREATE TABLE IF NOT EXISTS PlayerData (
	UUID VARCHAR(36) NOT NULL,
	LastSeenName VARCHAR(16) NOT NULL,
	Prefix VARCHAR(100), Nick VARCHAR(100),
	Emeralds INT NOT NULL DEFAULT 0,
	KillStreak INT NOT NULL DEFAULT 0,
	EloRating INT NOT NULL DEFAULT 1000,
	PRIMARY KEY (UUID)
);

CREATE TABLE IF NOT EXISTS SeasonStats (
	UUID VARCHAR(36) NOT NULL,
	Season TINYINT NOT NULL,
	Kills SMALLINT NOT NULL DEFAULT 0,
	Deaths SMALLINT NOT NULL DEFAULT 0,
	MonumentsDestroyed SMALLINT NOT NULL DEFAULT 0,
	Wins SMALLINT NOT NULL DEFAULT 0,
	Losses SMALLINT NOT NULL DEFAULT 0,
	PlayTimeWon INT NOT NULL DEFAULT 0,
	PlayTimeLost INT NOT NULL DEFAULT 0,
	LongestKillStreak INT NOT NULL DEFAULT 0,
	FOREIGN KEY (UUID) REFERENCES PlayerData(UUID),
	PRIMARY KEY (UUID, Season)
);