main: dtmproject.common.DTM
name: DTM
version: 6.0.0
author: Juubes
website: https://github.com/DTMProject/DTM
depend:
- ProtocolLib
database: true
api-version: 1.12.2
commands:
   DTM: {}
   top: {}
   shop:
      aliases:
      - s
      - k
      - kauppa
   join:
      aliases:
      - liity
   spec:
      aliases:
      - spectate
      - leave
   pause: null
   getpos: null
   worlds: null
   world: null
   stats: null
   nextmap: null
   setlobby: null
   editmode: null
   savekit:
      aliases:
      - gameinventory
   addteam: null
   removeteam:
      aliases:
      - delteam
   setteamspawn:
      aliases:
      - setspawn
   start: null
   setprefix: null
   savemap: null
   playtime:
      aliases:
      - gametime
   setmonument: {}